export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_QUIZCATEGORIES = 'GET_QUIZCATEGORIES';
export const SET_LOADING = 'SET_LOADING';
export const QUIZCATEGORIES_ERROR = 'QUIZCATEGORIES_ERROR';
export const HANDLE_SELECT = 'HANDLE_SELECT';
export const HANDLE_DIFFICULTY = 'HANDLE_DIFFICULTY';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const GET_FETCHCATEGORIES = 'GET_FETCHCATEGORIES';
export const HANDLE_SUBMIT = 'HANDLE_SUBMIT';

export const RESET_QUIZ = 'RESET_QUIZ';
export const SETCURRENT_QUIZSTEP = 'SETCURRENT_QUIZSTEP';
